### ISSUE TITLE
Reset cache directory

### ISSUE THREAD

**Issue by kleineroscar** [las3rlars/wxSpot#2]
When I first opened wxSpot I set the cache on a read only drive. WxSpot doesn't open at all now. Is there any way to reset it?

**Comment by las3rlars** [comment]
Oh! :) Someone else than myself using wxSpot! You just gave me a good boost of motivation on continuing coding on it!

Do you mind giving a short description of how you triggered your issue?

The value can be set manually with the help of regedit:

run regedit;

find; HKEY_CURRENT_USER -> SOFTWARE -> wxSpot

There you will the configuration.

Best regards

**Comment by kleineroscar** [comment]
Haha great.I'm using wxSpot on a Bootcamp partition on my Mac. There you have access to your Macintosh HD partition but it's read only. When I first downloaded wxSpot I set the directory for the macintosh HD, because I had more space there. Then wxSpot crashed and whenever I tried to open it again it crashed immediately. Also I seem to not be able to open my playlists, but the search and playback works fine, should I open another issue for that? 

```
    _____________________________
```

**Comment by las3rlars** [comment]
I posted a new version for you - not sure which one you are using, Give this one a try! The cache folder is for the spotify library to cache files - I haven't really thought of checking if that directory is read-only. I'll add that to my TODO. Could you try the latest version and see if you still have issues with your playlists?

Best Regards

**Comment by kleineroscar** [comment]
Yes the new version fixed my issue. Thank you very much!
